const {spawn}=require('node:child_process');
const {mkdtempSync,rmSync}=require('node:fs');
const {tmpdir}=require('node:os');
const {join}=require('node:path');
const assert=require('node:assert/strict');
const folder=mkdtempSync(join(tmpdir(),'inventrack-test-'));
const port=31873;
let child;
async function start(){
 child=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:String(port),DB_PATH:join(folder,'test.db')},stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{child.stdout.once('data',resolve);child.once('error',reject);child.once('exit',code=>reject(Error(`Server exited ${code}`)));});
}
async function stop(){await new Promise(resolve=>{child.once('exit',resolve);child.kill();});}
const get=async path=>fetch(`http://localhost:${port}${path}`);
const put=async data=>fetch(`http://localhost:${port}/api/inventory`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const post=async(path,data)=>fetch(`http://localhost:${port}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
(async()=>{try{
 await start();const initial=await (await get('/api/inventory')).json();
 assert.equal(initial.shipments.length,6);
 const changed=structuredClone(initial);changed.products[0].name='Persistence verification';
 changed.shipments[0].status='delivered';
 assert.equal((await put(changed)).status,200);
 assert.equal((await put(initial)).status,409);
 const latest=await (await get('/api/inventory')).json();const invalid=structuredClone(latest);invalid.products[0].quantity=-1;
 assert.equal((await put(invalid)).status,400);
 const invalidShipment=structuredClone(latest);invalidShipment.shipments[0].status='unknown';
 assert.equal((await put(invalidShipment)).status,400);
 assert.equal((await (await get('/api/inventory')).json()).products.find(p=>p.name==='Persistence verification').quantity,changed.products[0].quantity);
 assert.equal((await (await get('/api/inventory')).json()).shipments[0].status,'delivered');
 const beforeStock=await (await get('/api/inventory')).json();
 const lowStockProduct=beforeStock.products.find(product=>product.id==='p2');
 const stockIn=await post('/api/stock-movements',{productId:lowStockProduct.id,type:'in',quantity:3,reference:'DELIVERY-1',notes:'Received'});
 assert.equal(stockIn.status,200);
 const afterStock=await stockIn.json();
 assert.equal(afterStock.products.find(product=>product.id===lowStockProduct.id).quantity,lowStockProduct.quantity+3);
 assert.equal(afterStock.movements.find(movement=>movement.reference==='DELIVERY-1').balance,lowStockProduct.quantity+3);
 assert.equal((await post('/api/stock-movements',{productId:lowStockProduct.id,type:'out',quantity:999999})).status,400);
 const directQuantity=structuredClone(afterStock);directQuantity.products.find(product=>product.id===lowStockProduct.id).quantity++;
 assert.equal((await put(directQuantity)).status,400);
 const barcodeSnapshot=structuredClone(afterStock);barcodeSnapshot.products.find(product=>product.id===lowStockProduct.id).barcode='9876543210001';
 const barcodeSave=await put(barcodeSnapshot);assert.equal(barcodeSave.status,200);
 const withBarcode=await barcodeSave.json();assert.equal(withBarcode.products.find(product=>product.id===lowStockProduct.id).barcode,'9876543210001');
 const orderResponse=await post('/api/purchase-orders',{supplierId:'s1',items:[{productId:lowStockProduct.id,quantity:5}]});
 assert.equal(orderResponse.status,201);
 const withOrder=await orderResponse.json(),order=withOrder.purchaseOrders[0];
 assert.equal(order.status,'ordered');assert.equal(order.items[0].quantity,5);
 const partialResponse=await post(`/api/purchase-orders/${order.id}/receive`,{items:[{productId:lowStockProduct.id,quantity:2}]});
 assert.equal(partialResponse.status,200);
 const partial=await partialResponse.json();assert.equal(partial.purchaseOrders[0].status,'partial');assert.equal(partial.purchaseOrders[0].items[0].receivedQuantity,2);
 assert.equal((await post(`/api/purchase-orders/${order.id}/receive`,{items:[{productId:lowStockProduct.id,quantity:4}]})).status,400);
 assert.equal((await (await get('/api/inventory')).json()).products.find(product=>product.id===lowStockProduct.id).quantity,lowStockProduct.quantity+5);
 const receiveResponse=await post(`/api/purchase-orders/${order.id}/receive`,{});assert.equal(receiveResponse.status,200);
 const received=await receiveResponse.json();
 assert.equal(received.purchaseOrders[0].status,'received');
 assert.equal(received.products.find(product=>product.id===lowStockProduct.id).quantity,lowStockProduct.quantity+8);
 assert.equal(received.movements.filter(movement=>movement.reference===order.id).reduce((total,movement)=>total+movement.quantity,0),5);
 assert.equal((await post(`/api/purchase-orders/${order.id}/receive`,{})).status,400);
 const snapshotWithoutHistory=structuredClone(received);snapshotWithoutHistory.movements=[];
 assert.equal((await put(snapshotWithoutHistory)).status,200);
 assert.ok((await (await get('/api/inventory')).json()).movements.some(movement=>movement.reference===order.id));
 for(const url of ['/server.js','/data/inventrack.db','/.git/config'])assert.equal((await get(url)).status,404);
 for(const url of ['/assets/earth-texture.png','/assets/products/p1.png','/assets/suppliers/s1.png'])assert.equal((await get(url)).status,200);
 assert.equal((await get('/runtime-config.js')).status,200);
 for(const url of ['/globe.js','/globe-math.js','/globe.css'])assert.equal((await get(url)).status,200);
 const earth=await get('/assets/earth-daymap.jpg');assert.equal(earth.status,200);assert.match(earth.headers.get('content-type'),/^image\/jpeg/);
 const borders=await (await get('/assets/countries-110m.json')).json();assert.equal(borders.type,'Topology');assert.ok(borders.arcs.length>100);
 const firstVisit=await post('/api/visits',{visitorId:'test-visitor-000001',path:'#analytics'});assert.equal(firstVisit.status,200);const firstVisitStats=await firstVisit.json();assert.equal(firstVisitStats.totalVisitors,1);assert.equal((await post('/api/visits',{visitorId:'test-visitor-000001',path:'#analytics'})).status,200);assert.equal((await (await get('/api/visits')).json()).totalVisitors,1);assert.equal((await post('/api/visits',{visitorId:'short',path:'#analytics'})).status,400);
 assert.equal((await get('/workspace.css')).status,200);
 assert.ok((await (await get('/api/releases')).json()).length);
 await stop();await start();assert.ok((await (await get('/api/inventory')).json()).products.some(p=>p.name==='Persistence verification'));
 const reset=await post('/api/demo-reset',{});assert.equal(reset.status,200);
 const restored=await reset.json();assert.equal(restored.purchaseOrders.length,0);assert.equal(restored.products.find(product=>product.id==='p2').quantity,7);
 console.log('PASS: persistence, stock transactions, barcodes, purchase orders, audit history, demo reset, validation, and private files.');
 }finally{if(child&&child.exitCode===null)await stop();rmSync(folder,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
